### PR TITLE
feat(TUP-21518) Remove CryptoHelper

### PR DESCRIPTION
**Pull request by bhe-talendbj**
**What is the current behavior?** (You should also link to an open issue here)
https://jira.talendforge.org/browse/TUP-21518

**What is the new behavior?**
No behavior changes, just rename AES

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [x] Other... Please describe: Refactor source code.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by pbabin** [comment]
@bhe-talendbj Two questions:
No migration issue identified with previous passwords encrypted?
Have the JUnit tests been successfully run?

**Comment by htyin** [comment]
org.talend.util version need update?

**Comment by bhe-talendbj** [comment]
This change only rename AES to BouncyCastleEncryption, so it should be no other impacts.
The change will be merged into 7.3.1 master branch. my understanding is that master branch of tmdm-common depends on master branch of tcommon-studio-se, if so then no version update required.

I am still working on this, this PR should be merged after https://github.com/Talend/tcommon-studio-se/pull/2655

**Comment by htyin** [comment]
Version of org.talend.utils is 7.2.1 now.
https://github.com/Talend/tmdm-common/blob/master/org.talend.mdm.base/pom.xml#L644

**Comment by hbhong** [comment]
The code is OK, but it impacts the webservice between the studio and MDM server, so the QA should do the test again for this PR. Especially in the communication between server and studio.

**Pull request merged**
